def  UnetInceptionResNetV2(inputs):
  inceptionResNetV2 = InceptionResNetV2(include_top=False,input_shape=(512,512,3),pooling=None)
  inceptionResNetV2.trainable = False
  conv2d = inceptionResNetV2.get_layer('conv2d')(inputs)
  batch_normalization = inceptionResNetV2.get_layer('batch_normalization')(conv2d)
  activation = inceptionResNetV2.get_layer('activation')(batch_normalization)
  conv2d_1 = inceptionResNetV2.get_layer('conv2d_1')(activation)
  batch_normalization_1 = inceptionResNetV2.get_layer('conv2d_1')(conv2d_1)
  activation_1 = inceptionResNetV2.get_layer('activation_1')(batch_normalization_1)
  conv2d_2 = inceptionResNetV2.get_layer('conv2d_2')(activation_1)
  batch_normalization_2 = inceptionResNetV2.get_layer('batch_normalization_2')(conv2d_2)
  activation_2 = inceptionResNetV2.get_layer('activation_2')(batch_normalization_2)#concate with 253
  max_pooling2d = inceptionResNetV2.get_layer('max_pooling2d')(activation_2)
  #---------------------------------------------------------------
  conv2d_3 = inceptionResNetV2.get_layer('conv2d_3')(max_pooling2d)
  batch_normalization_3 = inceptionResNetV2.get_layer('batch_normalization_3')(conv2d_3)
  activation_3 = inceptionResNetV2.get_layer('activation_3')(batch_normalization_3)
  conv2d_4 = inceptionResNetV2.get_layer('conv2d_4')(activation_3)
  batch_normalization_4 = inceptionResNetV2.get_layer('batch_normalization_4')(conv2d_4)
  activation_4 = inceptionResNetV2.get_layer('activation_4')(batch_normalization_4)#concate with 124
  max_pooling2d_1 = inceptionResNetV2.get_layer('max_pooling2d_1')(activation_4)
  #---------------------------------------------------------------
  conv2d_8 = inceptionResNetV2.get_layer('conv2d_8')(max_pooling2d_1)
  batch_normalization_8 = inceptionResNetV2.get_layer('batch_normalization_8')(conv2d_8)
  activation_8 = inceptionResNetV2.get_layer('activation_8')(batch_normalization_8)
  conv2d_6 = inceptionResNetV2.get_layer('conv2d_6')(max_pooling2d_1)
  conv2d_9 = inceptionResNetV2.get_layer('conv2d_9')(activation_8)
  batch_normalization_6 = inceptionResNetV2.get_layer('batch_normalization_6')(conv2d_6)
  batch_normalization_9 = inceptionResNetV2.get_layer('batch_normalization_9')(conv2d_9)
  activation_6 = inceptionResNetV2.get_layer('activation_6')(batch_normalization_6)
  activation_9 = inceptionResNetV2.get_layer('activation_9')(batch_normalization_9)
  average_pooling2d = inceptionResNetV2.get_layer('average_pooling2d')(max_pooling2d_1)
  #---------------------------------------------------------------
  conv2d_5 = inceptionResNetV2.get_layer('conv2d_5')(max_pooling2d_1)
  conv2d_7 = inceptionResNetV2.get_layer('conv2d_7')(activation_6)
  conv2d_10 = inceptionResNetV2.get_layer('conv2d_10')(activation_9)
  conv2d_11 = inceptionResNetV2.get_layer('conv2d_11')(average_pooling2d)
  batch_normalization_5 = inceptionResNetV2.get_layer('batch_normalization_5')(conv2d_5)
  batch_normalization_7 = inceptionResNetV2.get_layer('batch_normalization_7')(conv2d_7)
  batch_normalization_10 = inceptionResNetV2.get_layer('batch_normalization_10')(conv2d_10)
  batch_normalization_11 = inceptionResNetV2.get_layer('batch_normalization_11')(conv2d_11)
  activation_5 = inceptionResNetV2.get_layer('activation_5')(batch_normalization_5)
  activation_7 = inceptionResNetV2.get_layer('activation_7')(batch_normalization_7)
  activation_10 = inceptionResNetV2.get_layer('activation_10')(batch_normalization_10)
  activation_11 = inceptionResNetV2.get_layer('activation_11')(batch_normalization_11)
  mixed_5b = inceptionResNetV2.get_layer('mixed_5b')([activation_5,activation_7,activation_10,activation_11])
  #-------------------------------------------------------------------------
  conv2d_15 = inceptionResNetV2.get_layer('conv2d_15')(mixed_5b)
  batch_normalization_15 = inceptionResNetV2.get_layer('batch_normalization_15')(conv2d_15)
  activation_15 = inceptionResNetV2.get_layer('activation_15')(batch_normalization_15)
  conv2d_13 = inceptionResNetV2.get_layer('conv2d_13')(mixed_5b)
  conv2d_16 = inceptionResNetV2.get_layer('conv2d_16')(activation_15)
  batch_normalization_13 = inceptionResNetV2.get_layer('batch_normalization_13')(conv2d_13)
  batch_normalization_16 = inceptionResNetV2.get_layer('batch_normalization_16')(conv2d_16)
  activation_13 = inceptionResNetV2.get_layer('activation_13')(batch_normalization_13)
  activation_16 = inceptionResNetV2.get_layer('activation_16')(batch_normalization_16)
  conv2d_12 = inceptionResNetV2.get_layer('conv2d_12')(mixed_5b)
  conv2d_14 = inceptionResNetV2.get_layer('conv2d_14')(activation_13)
  conv2d_17 = inceptionResNetV2.get_layer('conv2d_17')(activation_16)
  batch_normalization_12 = inceptionResNetV2.get_layer('batch_normalization_12')(conv2d_12)
  batch_normalization_14 = inceptionResNetV2.get_layer('batch_normalization_14')(conv2d_14)
  batch_normalization_17 = inceptionResNetV2.get_layer('batch_normalization_17')(conv2d_17)
  activation_12 = inceptionResNetV2.get_layer('activation_12')(batch_normalization_12)
  activation_14 = inceptionResNetV2.get_layer('activation_14')(batch_normalization_14)
  activation_17 = inceptionResNetV2.get_layer('activation_17')(batch_normalization_17)
  block35_1_mixed = inceptionResNetV2.get_layer('block35_1_mixed')([activation_12,activation_14,activation_17])
  block35_1_conv = inceptionResNetV2.get_layer('block35_1_conv')(block35_1_mixed)
  block35_1 = inceptionResNetV2.get_layer('block35_1')([mixed_5b,block35_1_conv])
  block35_1_ac = inceptionResNetV2.get_layer('block35_1_ac')(block35_1)
  #-------------------------------------------------------------------------
  conv2d_21 = inceptionResNetV2.get_layer('conv2d_21')(block35_1_ac)
  batch_normalization_21 = inceptionResNetV2.get_layer('batch_normalization_21')(conv2d_21)
  activation_21 = inceptionResNetV2.get_layer('activation_21')(batch_normalization_21)
  conv2d_19 = inceptionResNetV2.get_layer('conv2d_19')(block35_1_ac)
  conv2d_22 = inceptionResNetV2.get_layer('conv2d_22')(activation_21)
  batch_normalization_19 = inceptionResNetV2.get_layer('batch_normalization_19')(conv2d_19)
  batch_normalization_22 = inceptionResNetV2.get_layer('batch_normalization_22')(conv2d_22)
  activation_19 = inceptionResNetV2.get_layer('activation_19')(batch_normalization_19)
  activation_22 = inceptionResNetV2.get_layer('activation_22')(batch_normalization_22)
  conv2d_18 = inceptionResNetV2.get_layer('conv2d_18')(block35_1_ac)
  conv2d_20 = inceptionResNetV2.get_layer('conv2d_20')(activation_19)
  conv2d_23 = inceptionResNetV2.get_layer('conv2d_23')(activation_22)
  batch_normalization_18 = inceptionResNetV2.get_layer('batch_normalization_18')(conv2d_18)
  batch_normalization_20 = inceptionResNetV2.get_layer('batch_normalization_20')(conv2d_20)
  batch_normalization_23 = inceptionResNetV2.get_layer('batch_normalization_23')(conv2d_23)
  activation_18 = inceptionResNetV2.get_layer('activation_18')(batch_normalization_18)
  activation_20 = inceptionResNetV2.get_layer('activation_20')(batch_normalization_20)
  activation_23 = inceptionResNetV2.get_layer('activation_23')(batch_normalization_23)
  block35_2_mixed = inceptionResNetV2.get_layer('block35_2_mixed')([activation_18,activation_20,activation_23])
  block35_2_conv = inceptionResNetV2.get_layer('block35_2_conv')(block35_2_mixed)
  block35_2 = inceptionResNetV2.get_layer('block35_2')([block35_1_ac,block35_2_conv])
  block35_2_ac = inceptionResNetV2.get_layer('block35_2_ac')(block35_2)
  #-------------------------------------------------------------------------
  conv2d_27 = inceptionResNetV2.get_layer('conv2d_27')(block35_2_ac)
  batch_normalization_27 = inceptionResNetV2.get_layer('batch_normalization_27')(conv2d_27)
  activation_27 = inceptionResNetV2.get_layer('activation_27')(batch_normalization_27)
  conv2d_25 = inceptionResNetV2.get_layer('conv2d_25')(block35_2_ac)
  conv2d_28 = inceptionResNetV2.get_layer('conv2d_28')(activation_27)
  batch_normalization_25 = inceptionResNetV2.get_layer('batch_normalization_25')(conv2d_25)
  batch_normalization_28 = inceptionResNetV2.get_layer('batch_normalization_28')(conv2d_28)
  activation_25 = inceptionResNetV2.get_layer('activation_25')(batch_normalization_25)
  activation_28 = inceptionResNetV2.get_layer('activation_28')(batch_normalization_28)
  conv2d_24 = inceptionResNetV2.get_layer('conv2d_24')(block35_2_ac)
  conv2d_26 = inceptionResNetV2.get_layer('conv2d_26')(activation_25)
  conv2d_29 = inceptionResNetV2.get_layer('conv2d_29')(activation_28)
  batch_normalization_24 = inceptionResNetV2.get_layer('batch_normalization_24')(conv2d_24)
  batch_normalization_26 = inceptionResNetV2.get_layer('batch_normalization_26')(conv2d_26)
  batch_normalization_29 = inceptionResNetV2.get_layer('batch_normalization_29')(conv2d_29)
  activation_24 = inceptionResNetV2.get_layer('activation_24')(batch_normalization_24)
  activation_26 = inceptionResNetV2.get_layer('activation_26')(batch_normalization_26)
  activation_29 = inceptionResNetV2.get_layer('activation_29')(batch_normalization_29)
  block35_3_mixed = inceptionResNetV2.get_layer('block35_3_mixed')([activation_24,activation_26,activation_29])
  block35_3_conv = inceptionResNetV2.get_layer('block35_3_conv')(block35_3_mixed)
  block35_3 = inceptionResNetV2.get_layer('block35_3')([block35_2_ac,block35_3_conv])
  block35_3_ac = inceptionResNetV2.get_layer('block35_3_ac')(block35_3)
  #-------------------------------------------------------------------------
  conv2d_33 = inceptionResNetV2.get_layer('conv2d_33')(block35_3_ac)
  batch_normalization_33 = inceptionResNetV2.get_layer('batch_normalization_33')(conv2d_33)
  activation_33 = inceptionResNetV2.get_layer('activation_33')(batch_normalization_33)
  conv2d_31 = inceptionResNetV2.get_layer('conv2d_31')(block35_3_ac)
  conv2d_34 = inceptionResNetV2.get_layer('conv2d_34')(activation_33)
  batch_normalization_31 = inceptionResNetV2.get_layer('batch_normalization_31')(conv2d_31)
  batch_normalization_34 = inceptionResNetV2.get_layer('batch_normalization_34')(conv2d_34)
  activation_31 = inceptionResNetV2.get_layer('activation_31')(batch_normalization_31)
  activation_34 = inceptionResNetV2.get_layer('activation_34')(batch_normalization_34)
  conv2d_30 = inceptionResNetV2.get_layer('conv2d_30')(block35_3_ac)
  conv2d_32 = inceptionResNetV2.get_layer('conv2d_32')(activation_31)
  conv2d_35 = inceptionResNetV2.get_layer('conv2d_35')(activation_34)
  batch_normalization_30 = inceptionResNetV2.get_layer('batch_normalization_30')(conv2d_30)
  batch_normalization_32 = inceptionResNetV2.get_layer('batch_normalization_32')(conv2d_32)
  batch_normalization_35 = inceptionResNetV2.get_layer('batch_normalization_35')(conv2d_35)
  activation_30 = inceptionResNetV2.get_layer('activation_30')(batch_normalization_30)
  activation_32 = inceptionResNetV2.get_layer('activation_32')(batch_normalization_32)
  activation_35 = inceptionResNetV2.get_layer('activation_35')(batch_normalization_35)
  block35_4_mixed = inceptionResNetV2.get_layer('block35_4_mixed')([activation_30,activation_32,activation_35])
  block35_4_conv = inceptionResNetV2.get_layer('block35_4_conv')(block35_4_mixed)
  block35_4 = inceptionResNetV2.get_layer('block35_4')([block35_3_ac,block35_4_conv])
  block35_4_ac = inceptionResNetV2.get_layer('block35_4_ac')(block35_4)
  #-------------------------------------------------------------------------
  conv2d_39 = inceptionResNetV2.get_layer('conv2d_39')(block35_4_ac)
  batch_normalization_39 = inceptionResNetV2.get_layer('batch_normalization_39')(conv2d_39)
  activation_39 = inceptionResNetV2.get_layer('activation_39')(batch_normalization_39)
  conv2d_37 = inceptionResNetV2.get_layer('conv2d_37')(block35_4_ac)
  conv2d_40 = inceptionResNetV2.get_layer('conv2d_40')(activation_39)
  batch_normalization_37 = inceptionResNetV2.get_layer('batch_normalization_37')(conv2d_37)
  batch_normalization_40 = inceptionResNetV2.get_layer('batch_normalization_40')(conv2d_40)
  activation_37 = inceptionResNetV2.get_layer('activation_37')(batch_normalization_37)
  activation_40 = inceptionResNetV2.get_layer('activation_40')(batch_normalization_40)
  conv2d_36 = inceptionResNetV2.get_layer('conv2d_36')(block35_4_ac)
  conv2d_38 = inceptionResNetV2.get_layer('conv2d_38')(activation_37)
  conv2d_41 = inceptionResNetV2.get_layer('conv2d_41')(activation_40)
  batch_normalization_36 = inceptionResNetV2.get_layer('batch_normalization_36')(conv2d_36)
  batch_normalization_38 = inceptionResNetV2.get_layer('batch_normalization_38')(conv2d_38)
  batch_normalization_41 = inceptionResNetV2.get_layer('batch_normalization_41')(conv2d_41)
  activation_36 = inceptionResNetV2.get_layer('activation_36')(batch_normalization_36)
  activation_38 = inceptionResNetV2.get_layer('activation_38')(batch_normalization_38)
  activation_41 = inceptionResNetV2.get_layer('activation_41')(batch_normalization_41)
  block35_5_mixed = inceptionResNetV2.get_layer('block35_5_mixed')([activation_36,activation_38,activation_41])
  block35_5_conv = inceptionResNetV2.get_layer('block35_5_conv')(block35_5_mixed)
  block35_5 = inceptionResNetV2.get_layer('block35_5')([block35_4_ac,block35_5_conv])
  block35_5_ac = inceptionResNetV2.get_layer('block35_5_ac')(block35_5)
  #-------------------------------------------------------------------------
  conv2d_45 = inceptionResNetV2.get_layer('conv2d_45')(block35_5_ac)
  batch_normalization_45= inceptionResNetV2.get_layer('batch_normalization_45')(conv2d_45)
  activation_45 = inceptionResNetV2.get_layer('activation_45')(batch_normalization_45)
  conv2d_43 = inceptionResNetV2.get_layer('conv2d_43')(block35_5_ac)
  conv2d_46 = inceptionResNetV2.get_layer('conv2d_46')(activation_45)
  batch_normalization_43 = inceptionResNetV2.get_layer('batch_normalization_43')(conv2d_43)
  batch_normalization_46 = inceptionResNetV2.get_layer('batch_normalization_46')(conv2d_46)
  activation_43 = inceptionResNetV2.get_layer('activation_43')(batch_normalization_43)
  activation_46 = inceptionResNetV2.get_layer('activation_46')(batch_normalization_46)
  conv2d_42 = inceptionResNetV2.get_layer('conv2d_42')(block35_5_ac)
  conv2d_44 = inceptionResNetV2.get_layer('conv2d_44')(activation_43)
  conv2d_47 = inceptionResNetV2.get_layer('conv2d_47')(activation_46)
  batch_normalization_42 = inceptionResNetV2.get_layer('batch_normalization_42')(conv2d_42)
  batch_normalization_44 = inceptionResNetV2.get_layer('batch_normalization_44')(conv2d_44)
  batch_normalization_47 = inceptionResNetV2.get_layer('batch_normalization_47')(conv2d_47)
  activation_42 = inceptionResNetV2.get_layer('activation_42')(batch_normalization_42)
  activation_44 = inceptionResNetV2.get_layer('activation_44')(batch_normalization_44)
  activation_47 = inceptionResNetV2.get_layer('activation_47')(batch_normalization_47)
  block35_6_mixed = inceptionResNetV2.get_layer('block35_6_mixed')([activation_42,activation_44,activation_47])
  block35_6_conv = inceptionResNetV2.get_layer('block35_6_conv')(block35_6_mixed)
  block35_6 = inceptionResNetV2.get_layer('block35_6')([block35_5_ac,block35_6_conv])
  block35_6_ac = inceptionResNetV2.get_layer('block35_6_ac')(block35_6)
  #-------------------------------------------------------------------------
  conv2d_51 = inceptionResNetV2.get_layer('conv2d_51')(block35_6_ac)
  batch_normalization_51 = inceptionResNetV2.get_layer('batch_normalization_51')(conv2d_51)
  activation_51 = inceptionResNetV2.get_layer('activation_51')(batch_normalization_51)
  conv2d_49 = inceptionResNetV2.get_layer('conv2d_49')(block35_6_ac)
  conv2d_52 = inceptionResNetV2.get_layer('conv2d_52')(activation_51)
  batch_normalization_49 = inceptionResNetV2.get_layer('batch_normalization_49')(conv2d_49)
  batch_normalization_52 = inceptionResNetV2.get_layer('batch_normalization_52')(conv2d_52)
  activation_49 = inceptionResNetV2.get_layer('activation_49')(batch_normalization_49)
  activation_52 = inceptionResNetV2.get_layer('activation_52')(batch_normalization_52)
  conv2d_48 = inceptionResNetV2.get_layer('conv2d_48')(block35_6_ac)
  conv2d_50 = inceptionResNetV2.get_layer('conv2d_50')(activation_49)
  conv2d_53 = inceptionResNetV2.get_layer('conv2d_53')(activation_52)
  batch_normalization_48 = inceptionResNetV2.get_layer('batch_normalization_48')(conv2d_48)
  batch_normalization_50 = inceptionResNetV2.get_layer('batch_normalization_50')(conv2d_50)
  batch_normalization_53 = inceptionResNetV2.get_layer('batch_normalization_53')(conv2d_53)
  activation_48 = inceptionResNetV2.get_layer('activation_48')(batch_normalization_48)
  activation_50 = inceptionResNetV2.get_layer('activation_50')(batch_normalization_50)
  activation_53 = inceptionResNetV2.get_layer('activation_53')(batch_normalization_53)
  block35_7_mixed = inceptionResNetV2.get_layer('block35_7_mixed')([activation_48,activation_50,activation_53])
  block35_7_conv = inceptionResNetV2.get_layer('block35_7_conv')(block35_7_mixed)
  block35_7 = inceptionResNetV2.get_layer('block35_7')([block35_6_ac,block35_7_conv])
  block35_7_ac = inceptionResNetV2.get_layer('block35_7_ac')(block35_7)
  #-------------------------------------------------------------------------
  conv2d_57 = inceptionResNetV2.get_layer('conv2d_57')(block35_7_ac)
  batch_normalization_57 = inceptionResNetV2.get_layer('batch_normalization_57')(conv2d_57)
  activation_57 = inceptionResNetV2.get_layer('activation_57')(batch_normalization_57)
  conv2d_55 = inceptionResNetV2.get_layer('conv2d_55')(block35_7_ac)
  conv2d_58 = inceptionResNetV2.get_layer('conv2d_58')(activation_57)
  batch_normalization_55 = inceptionResNetV2.get_layer('batch_normalization_55')(conv2d_55)
  batch_normalization_58 = inceptionResNetV2.get_layer('batch_normalization_58')(conv2d_58)
  activation_55 = inceptionResNetV2.get_layer('activation_55')(batch_normalization_55)
  activation_58 = inceptionResNetV2.get_layer('activation_58')(batch_normalization_58)
  conv2d_54 = inceptionResNetV2.get_layer('conv2d_54')(block35_7_ac)
  conv2d_56 = inceptionResNetV2.get_layer('conv2d_56')(activation_55)
  conv2d_59 = inceptionResNetV2.get_layer('conv2d_59')(activation_58)
  batch_normalization_54 = inceptionResNetV2.get_layer('batch_normalization_54')(conv2d_54)
  batch_normalization_56 = inceptionResNetV2.get_layer('batch_normalization_56')(conv2d_56)
  batch_normalization_59 = inceptionResNetV2.get_layer('batch_normalization_59')(conv2d_59)
  activation_54 = inceptionResNetV2.get_layer('activation_54')(batch_normalization_54)
  activation_56 = inceptionResNetV2.get_layer('activation_56')(batch_normalization_56)
  activation_59 = inceptionResNetV2.get_layer('activation_59')(batch_normalization_59)
  block35_8_mixed = inceptionResNetV2.get_layer('block35_8_mixed')([activation_54,activation_56,activation_59])
  block35_8_conv = inceptionResNetV2.get_layer('block35_8_conv')(block35_8_mixed)
  block35_8 = inceptionResNetV2.get_layer('block35_8')([block35_7_ac,block35_8_conv])
  block35_8_ac = inceptionResNetV2.get_layer('block35_8_ac')(block35_8)
  #-------------------------------------------------------------------------
  conv2d_63 = inceptionResNetV2.get_layer('conv2d_63')(block35_8_ac)
  batch_normalization_63 = inceptionResNetV2.get_layer('batch_normalization_63')(conv2d_63)
  activation_63 = inceptionResNetV2.get_layer('activation_63')(batch_normalization_63)
  conv2d_61 = inceptionResNetV2.get_layer('conv2d_61')(block35_8_ac)
  conv2d_64 = inceptionResNetV2.get_layer('conv2d_64')(activation_63)
  batch_normalization_61 = inceptionResNetV2.get_layer('batch_normalization_61')(conv2d_61)
  batch_normalization_64 = inceptionResNetV2.get_layer('batch_normalization_64')(conv2d_64)
  activation_61 = inceptionResNetV2.get_layer('activation_61')(batch_normalization_61)
  activation_64 = inceptionResNetV2.get_layer('activation_64')(batch_normalization_64)
  conv2d_60 = inceptionResNetV2.get_layer('conv2d_60')(block35_8_ac)
  conv2d_62 = inceptionResNetV2.get_layer('conv2d_62')(activation_61)
  conv2d_65 = inceptionResNetV2.get_layer('conv2d_65')(activation_64)
  batch_normalization_60 = inceptionResNetV2.get_layer('batch_normalization_60')(conv2d_60)
  batch_normalization_62 = inceptionResNetV2.get_layer('batch_normalization_62')(conv2d_62)
  batch_normalization_65 = inceptionResNetV2.get_layer('batch_normalization_65')(conv2d_65)
  activation_60 = inceptionResNetV2.get_layer('activation_60')(batch_normalization_60)
  activation_62 = inceptionResNetV2.get_layer('activation_62')(batch_normalization_62)
  activation_65 = inceptionResNetV2.get_layer('activation_65')(batch_normalization_65)
  block35_9_mixed = inceptionResNetV2.get_layer('block35_9_mixed')([activation_60,activation_62,activation_65])
  block35_9_conv = inceptionResNetV2.get_layer('block35_9_conv')(block35_9_mixed)
  block35_9 = inceptionResNetV2.get_layer('block35_9')([block35_8_ac,block35_9_conv])
  block35_9_ac = inceptionResNetV2.get_layer('block35_9_ac')(block35_9)
  #-------------------------------------------------------------------------
  conv2d_69 = inceptionResNetV2.get_layer('conv2d_69')(block35_9_ac)
  batch_normalization_69 = inceptionResNetV2.get_layer('batch_normalization_69')(conv2d_69)
  activation_69 = inceptionResNetV2.get_layer('activation_69')(batch_normalization_69)
  conv2d_67 = inceptionResNetV2.get_layer('conv2d_67')(block35_9_ac)
  conv2d_70 = inceptionResNetV2.get_layer('conv2d_70')(activation_69)
  batch_normalization_67 = inceptionResNetV2.get_layer('batch_normalization_67')(conv2d_67)
  batch_normalization_70 = inceptionResNetV2.get_layer('batch_normalization_70')(conv2d_70)
  activation_67 = inceptionResNetV2.get_layer('activation_67')(batch_normalization_67)
  activation_70 = inceptionResNetV2.get_layer('activation_70')(batch_normalization_70)
  conv2d_66 = inceptionResNetV2.get_layer('conv2d_66')(block35_9_ac)
  conv2d_68 = inceptionResNetV2.get_layer('conv2d_68')(activation_67)
  conv2d_71 = inceptionResNetV2.get_layer('conv2d_71')(activation_70)
  batch_normalization_66 = inceptionResNetV2.get_layer('batch_normalization_66')(conv2d_66)
  batch_normalization_68 = inceptionResNetV2.get_layer('batch_normalization_68')(conv2d_68)
  batch_normalization_71 = inceptionResNetV2.get_layer('batch_normalization_71')(conv2d_71)
  activation_66 = inceptionResNetV2.get_layer('activation_66')(batch_normalization_66)
  activation_68 = inceptionResNetV2.get_layer('activation_68')(batch_normalization_68)
  activation_71 = inceptionResNetV2.get_layer('activation_71')(batch_normalization_71)
  block35_10_mixed = inceptionResNetV2.get_layer('block35_10_mixed')([activation_66,activation_68,activation_71])
  block35_10_conv = inceptionResNetV2.get_layer('block35_10_conv')(block35_10_mixed)
  block35_10 = inceptionResNetV2.get_layer('block35_10')([block35_9_ac,block35_10_conv])
  block35_10_ac = inceptionResNetV2.get_layer('block35_10_ac')(block35_10)
  #-------------------------------------------------------------------------
  conv2d_73 = inceptionResNetV2.get_layer('conv2d_73')(block35_10_ac)
  batch_normalization_73 = inceptionResNetV2.get_layer('batch_normalization_73')(conv2d_73)
  activation_73 = inceptionResNetV2.get_layer('activation_73')(batch_normalization_73)
  conv2d_74 = inceptionResNetV2.get_layer('conv2d_74')(activation_73)
  batch_normalization_74 = inceptionResNetV2.get_layer('batch_normalization_74')(conv2d_74)
  activation_74 = inceptionResNetV2.get_layer('activation_74')(batch_normalization_74)
  #-------------------------------------------------------------------------
  # maxpool = MaxPool2D()(mixed2)

  # conv5 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(maxpool)
  # conv5 = Conv2D(512, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv5)
  # drop5 = Dropout(0.5)(conv5)

  up6 = Conv2D(192, (2,2), activation = 'relu', padding = 'valid', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(activation_74))
  up6 = tf.keras.layers.ZeroPadding2D(padding=1)(up6)
  up6 = tf.keras.layers.ZeroPadding2D(padding=1)(up6)

  merge6 = concatenate([activation_3,up6], axis = 3)
  conv6 = Conv2D(192, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge6)
  conv6 = Conv2D(192, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv6)

  up7 = Conv2D(64, 2, activation = 'relu', padding = 'valid', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv6))
  up7 = tf.keras.layers.ZeroPadding2D(padding=1)(up7)
  up7 = tf.keras.layers.ZeroPadding2D(padding=1)(up7)
  up7 = tf.keras.layers.ZeroPadding2D(padding=1)(up7)
  merge7 = concatenate([conv2d,up7], axis = 3)
  conv7 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge7)
  conv7 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv7)

  up8 = Conv2D(24, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv7))

  up8 = tf.keras.layers.ZeroPadding2D(padding=1)(up8)
  # merge8 = concatenate([activation_2,up8], axis = 3)
  # conv8 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(merge8)
  # conv8 = Conv2D(128, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(conv8)

  # up9 = Conv2D(64, 2, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(UpSampling2D(size = (2,2))(conv8))
  # # merge9 = concatenate([conv1,up9], axis = 3)
  # conv9 = Conv2D(64, 3, activation = 'relu', padding = 'same', kernel_initializer = 'he_normal')(up9)
  conv10 = Conv2D(1, 1, activation = 'sigmoid')(up8)

  model = Model(inputs, conv10)
  return model